[package]
name = "tokio-debug"
version = "0.1.0"
edition = "2024"

[dependencies]
console-subscriber = "0.4.1"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "parking_lot", "time", "tracing"] }
tracing = "0.1.41"
