[package]
name = "patch-num-cpus"
version = "0.1.0"
edition = "2024"

[dependencies]
num_cpus = { git = "https://github.com/brndnmtthws/num_cpus", rev = "9b146fa" }

[patch.crates-io]
libc = { git = "https://github.com/rust-lang/libc", tag = "0.2.171" }
