[package]
name = "tokio-console"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = {version = "0.1.41"}
tokio = {version = "1.42", features = ["macros", "rt-multi-thread", "time"]}
console-subscriber = {version = "0.4"}